Run, "%userprofile%\Downloads\mimiroot\root.bat"
Run, "%userprofile%\Downloads\mimiroot\rootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootrootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootqe.root.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootqk.root.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootgq.root.bat"
Run, "%userprofile%\Downloads\mimiroot\root.bat"
Run, "%userprofile%\Downloads\mimiroot\rootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootrootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootqe.root.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootqk.root.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootgq.root.bat"
Run, "%userprofile%\Downloads\mimiroot\root.bat"
Run, "%userprofile%\Downloads\mimiroot\rootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\rootrootrootrootroot.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootqe.root.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootqk.root.bat"
Run, "%userprofile%\Downloads\mimiroot\otimizações básicas\rootgq.root.bat"
